<?php

namespace Kmrifat\Shopify\Providers;


use Kmrifat\Shopify\Socialites\SocialiteShopifyProvider;
use Illuminate\Support\ServiceProvider;
use Laravel\Socialite\Contracts\Factory;

class SocialiteDriverProvider extends ServiceProvider
{

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }

    public function boot(): void
    {
        $socialite = $this->app->make(Factory::class);

        $socialite->extend('shopify', function () use ($socialite) {
            $config = config('shopify');
            return $socialite->buildProvider(SocialiteShopifyProvider::class, $config);
        });
    }
}
